theme: jekyll-theme-chirpy

lang: en
timezone: Europe/Helsinki

title: Joost Oostdijk
tagline: Notes on software, hardware, AI, cycling, forestry and whatever else I'm tinkering with.
description: >-
  Notes on software, hardware, AI, cycling, forestry and whatever else I'm tinkering with.

url: "https://www.joostoostdijk.com"
baseurl: ""

github:
  username: joustava

social:
  name: Joost Oostdijk
  links:
    - https://github.com/joustava
    - https://www.linkedin.com/in/joostoostdijk/

theme_mode: light

avatar: /assets/images/me/joost.jpg

toc: true

comments:
  provider: ""

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: true
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - .gitignore
  - README.md
  - justfile
  - Gemfile
  - Gemfile.lock
  - "*.gem"

plugins:
  - jekyll-gist
