# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Joost Oostdijk
# https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-subtitle
subtitle: My dumping ground for notes
# https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-name
name: Joost Oostdijk
email: joustava@gmail.com
# Write an awesome description for your new site here. You can edit this
# line in _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.
description: >- # this means to ignore newlines until "baseurl:"
  Mostly a technical blog containing articles about stuff I do and create in my free time.

# https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-url
url: "https://joostoostdijk.com" # the base hostname & protocol for your site, e.g. http://example.com
# https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-base-url
baseurl: "" # the subpath of your site, e.g. /blog
timezone: Europe/Berlin
locale: "en"
# https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-repository
repository: joustava/joustava.github.io
permalink: /posts/:title

compress_html:
  clippings: all
  comments: all
  endings: all
  blanklines: false
  profile: false
  startings: all
  # ignore:
  #   envs: development # disable compression in dev environment

defaults:
  - # sitemap ignores
    scope:
      path: "_layouts/**/*.html"
    values:
      sitemap: false
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      # classes: wide
      author_profile: true
      author: Joost Oostdijk
  - scope:
      path: ""
      type: drafts
    values:
      layout: single
      # classes: wide
      author: Joost Oostdijk
      author_profile: true
      read_time: true
      show_date: true
      comments: true
      share: true
      related: true
      toc: true
      toc_sticky: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      # classes: wide
      author: Joost Oostdijk
      author_profile: true
      read_time: true
      show_date: true
      comments: true
      share: true
      related: true
      toc: true
      toc_sticky: true

twitter_username: joustava
github_username: joustava

# Build settings

remote_theme: mmistakes/minimal-mistakes #@4.20.2
minimal_mistakes_skin: "dark" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

# In technical material, the average reading rate is approx 50 to 75 words a minute roughly 5 to 6 minutes per page.
words_per_minute: 100
search: true
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-120964434-1"
    anonymize_ip: false # default
twitter:
  username: "joustava"

comments:
  provider: "disqus"
  disqus:
    shortname: "https-joostoostdijk-com"
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-last-modified-at

jekyll_compose:
  auto_open: true

include: ["_pages", "_layouts"]

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - README.md
  - Makefile
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
